export const languages = {
  'af': { label: 'Afrikaans', direction: 'ltr' },
  'sq': { label: 'Albanian', direction: 'ltr' },
  'am': { label: 'Amharic', direction: 'ltr' },
  'ar': { label: 'Arabic', direction: 'rtl' },
  'hy': { label: 'Armenian', direction: 'ltr' },
  'as': { label: 'Assamese', direction: 'ltr' },
  'ay': { label: 'Aymara', direction: 'ltr' },
  'az': { label: 'Azerbaijani', direction: 'ltr' },
  'bm': { label: 'Bambara', direction: 'ltr' },
  'eu': { label: 'Basque', direction: 'ltr' },
  'be': { label: 'Belarusian', direction: 'ltr' },
  'bn': { label: 'Bengali', direction: 'ltr' },
  'bho': { label: 'Bhojpuri', direction: 'ltr' },
  'bs': { label: 'Bosnian', direction: 'ltr' },
  'bg': { label: 'Bulgarian', direction: 'ltr' },
  'ca': { label: 'Catalan', direction: 'ltr' },
  'ceb': { label: 'Cebuano', direction: 'ltr' },
  'zh-CN': { label: 'Chinese (Simplified)', direction: 'ltr' },
  'zh-TW': { label: 'Chinese (Traditional)', direction: 'ltr' },
  'hr': { label: 'Croatian', direction: 'ltr' },
  'co': { label: 'Corsican', direction: 'ltr' },
  'cs': { label: 'Czech', direction: 'ltr' },
  'da': { label: 'Danish', direction: 'ltr' },
  'dv': { label: 'Dhivehi', direction: 'rtl' },
  'doi': { label: 'Dogri', direction: 'rtl' },
  'nl': { label: 'Dutch', direction: 'ltr' },
  'en': { label: 'English', direction: 'ltr' },
  'eo': { label: 'Esperanto', direction: 'ltr' },
  'et': { label: 'Estonian', direction: 'ltr' },
  'ee': { label: 'Ewe', direction: 'ltr' },
  'fil': { label: 'Filipino (Tagalog)', direction: 'ltr' },
  'tl': { label: 'Tagalog (Filipino)', direction: 'ltr' },
  'fi': { label: 'Finnish', direction: 'ltr' },
  'fr': { label: 'French', direction: 'ltr' },
  'fy': { label: 'Frisian', direction: 'ltr' },
  'gl': { label: 'Galician', direction: 'ltr' },
  'ka': { label: 'Georgian', direction: 'ltr' },
  'de': { label: 'German', direction: 'ltr' },
  'el': { label: 'Greek', direction: 'ltr' },
  'gn': { label: 'Guarani', direction: 'ltr' },
  'gu': { label: 'Gujarati', direction: 'ltr' },
  'ht': { label: 'Haitian (Creole)', direction: 'ltr' },
  'ha': { label: 'Hausa', direction: 'rtl' },
  'haw': { label: 'Hawaiian', direction: 'ltr' },
  'iw': { label: 'Hebrew', direction: 'rtl' },
  'hi': { label: 'Hindi', direction: 'ltr' },
  'hmn': { label: 'Hmong', direction: 'ltr' },
  'hu': { label: 'Hungarian', direction: 'ltr' },
  'is': { label: 'Icelandic', direction: 'ltr' },
  'ig': { label: 'Igbo', direction: 'ltr' },
  'ilo': { label: 'Ilocano', direction: 'ltr' },
  'id': { label: 'Indonesian', direction: 'ltr' },
  'ga': { label: 'Irish', direction: 'ltr' },
  'it': { label: 'Italian', direction: 'ltr' },
  'ja': { label: 'Japanese', direction: 'ltr' },
  'jv': { label: 'Javanese', direction: 'ltr' },
  'kn': { label: 'Kannada', direction: 'ltr' },
  'kk': { label: 'Kazakh', direction: 'rtl' },
  'km': { label: 'Khmer', direction: 'ltr' },
  'rw': { label: 'Kinyarwanda', direction: 'ltr' },
  'gom': { label: 'Konkani', direction: 'ltr' },
  'ko': { label: 'Korean', direction: 'ltr' },
  'kri': { label: 'Krio', direction: 'ltr' },
  'ku': { label: 'Kurdish', direction: 'rtl' },
  'ckb': { label: 'Kurdish (Sorani)', direction: 'rtl' },
  'ky': { label: 'Kyrgyz', direction: 'rtl' },
  'lo': { label: 'Lao', direction: 'ltr' },
  'la': { label: 'Latin', direction: 'ltr' },
  'lv': { label: 'Latvian', direction: 'ltr' },
  'ln': { label: 'Lingala', direction: 'ltr' },
  'lt': { label: 'Lithuanian', direction: 'ltr' },
  'lg': { label: 'Luganda', direction: 'ltr' },
  'lb': { label: 'Luxembourgish', direction: 'ltr' },
  'mk': { label: 'Macedonian', direction: 'ltr' },
  'mai': { label: 'Maithili', direction: 'ltr' },
  'mg': { label: 'Malagasy', direction: 'ltr' },
  'ms': { label: 'Malay', direction: 'ltr' },
  'ml': { label: 'Malayalam', direction: 'rtl' },
  'mt': { label: 'Maltese', direction: 'ltr' },
  'mi': { label: 'Maori', direction: 'ltr' },
  'mr': { label: 'Marathi', direction: 'ltr' },
  'mni-Mtei': { label: 'Meiteilon (Manipuri)', direction: 'ltr' },
  'lus': { label: 'Mizo', direction: 'ltr' },
  'mn': { label: 'Mongolian', direction: 'ltr' },
  'my': { label: 'Myanmar (Burmese)', direction: 'ltr' },
  'ne': { label: 'Nepali', direction: 'ltr' },
  'no': { label: 'Norwegian', direction: 'ltr' },
  'ny': { label: 'Nyanja (Chichewa)', direction: 'ltr' },
  'or': { label: 'Odia (Oriya)', direction: 'ltr' },
  'om': { label: 'Oromo', direction: 'ltr' },
  'ps': { label: 'Pashto', direction: 'rtl' },
  'fa': { label: 'Persian', direction: 'rtl' },
  'pl': { label: 'Polish', direction: 'ltr' },
  'pt': { label: 'Portuguese', direction: 'ltr' },
  'pa': { label: 'Punjabi', direction: 'ltr' },
  'qu': { label: 'Quechua', direction: 'ltr' },
  'ro': { label: 'Romanian', direction: 'ltr' },
  'ru': { label: 'Russian', direction: 'ltr' },
  'sm': { label: 'Samoan', direction: 'ltr' },
  'sa': { label: 'Sanskrit', direction: 'ltr' },
  'gd': { label: 'Scots Gaelic', direction: 'ltr' },
  'nso': { label: 'Sepedi', direction: 'ltr' },
  'sr': { label: 'Serbian', direction: 'ltr' },
  'st': { label: 'Sesotho', direction: 'ltr' },
  'sn': { label: 'Shona', direction: 'ltr' },
  'sd': { label: 'Sindhi', direction: 'ltr' },
  'si': { label: 'Sinhala (Sinhalese)', direction: 'ltr' },
  'sk': { label: 'Slovak', direction: 'ltr' },
  'sl': { label: 'Slovenian', direction: 'ltr' },
  'so': { label: 'Somali', direction: 'rtl' },
  'es': { label: 'Spanish', direction: 'ltr' },
  'su': { label: 'Sundanese', direction: 'rtl' },
  'sw': { label: 'Swahili', direction: 'ltr' },
  'sv': { label: 'Swedish', direction: 'ltr' },
  'tg': { label: 'Tajik', direction: 'rtl' },
  'ta': { label: 'Tamil', direction: 'ltr' },
  'tt': { label: 'Tatar', direction: 'ltr' },
  'te': { label: 'Telugu', direction: 'ltr' },
  'th': { label: 'Thai', direction: 'ltr' },
  'ti': { label: 'Tigrinya', direction: 'ltr' },
  'ts': { label: 'Tsonga', direction: 'ltr' },
  'tr': { label: 'Turkish', direction: 'ltr' },
  'tk': { label: 'Turkmen', direction: 'rtl' },
  'ak': { label: 'Twi (Akan)', direction: 'ltr' },
  'uk': { label: 'Ukrainian', direction: 'ltr' },
  'ur': { label: 'Urdu', direction: 'rtl' },
  'ug': { label: 'Uyghur', direction: 'rtl' },
  'uz': { label: 'Uzbek', direction: 'rtl' },
  'vi': { label: 'Vietnamese', direction: 'ltr' },
  'cy': { label: 'Welsh', direction: 'ltr' },
  'xh': { label: 'Xhosa', direction: 'ltr' },
  'yi': { label: 'Yiddish', direction: 'rtl' },
  'yo': { label: 'Yoruba', direction: 'rtl' },
  'zu': { label: 'Zulu', direction: 'ltr' },
}
